apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: kubernetes-email-alerts
  namespace: monitoring
  labels:
    alertmanagerConfig: main

spec:
  route:
    receiver: kubernetes-admin-email

    groupBy:
      - alertname
      - component

    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 30m

    matchers:
      - name: team
        value: kubernetes
        matchType: "="

  receivers:
    - name: kubernetes-admin-email

      emailConfigs:
        - sendResolved: true

          to: "gafarioladele1@example.com"
          from: "gafarioladele1@gmail.com"

          smarthost: "smtp.gmail.com:587"

          authUsername: "gafarioladele1@gmail.com"
          authIdentity: "gafarioladele1@gmail.com"

          authPassword:
            name: alertmanager-email-secret
            key: password

          requireTLS: true