apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-email-secret
  namespace: monitoring
type: Opaque
stringData:
  password: REPLACE_WITH_GMAIL_APP_PASSWORD

---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
type: Opaque
stringData:
  webhook-url: REPLACE_WITH_SLACK_WEBHOOK_URL